name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.7
  - pip=22.3.1
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - torchvision=0.14.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
