name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.11.7
  - pip=22.3.1
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - tqdm
  - ninja
  - cmake
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
